support x86 (32bits) arch
melynx/peekaboo pull request #1
Opened 2020-03-09 13:16 UTC by jun-zeng

Please use read_trace_zj.py in pypeekaboo folder to read x86 (32 bits) trace. I have generated a 'ls' trace in Ubuntu 16.04 32bits VM for you to test the results. You can download it with the following link. 

https://drive.google.com/open?id=1coiILZ_6BjBqr6Ij01oIAG_ZHalWQM39
MD5 checksum: 949e473efa552ff76a0d1901ac7fd7be

2020-03-09 13:24 UTC, mimicji requested changes
Please clean up all temp files before merging. 

Thanks.

2020-03-10 03:02 UTC, melynx reviewed
Why do you need to specifically create a 32bit store for the buffer?

2020-03-10 03:52 UTC, jun-zeng commented
This is because the size of pc in X86 arch is 4 bytes. If the program still uses OPND_CREATE_INT64 in drx_buf_insert_buf_store function, it will cause incompatible type error. 

We can also use type casting to solve this incompatibility problem if you don't like 32-bit buffer.

<img width="1105" alt="compile_error" src="https://user-images.githubusercontent.com/43632311/76277886-0a5a7080-62c5-11ea-8c6a-fcf39356e000.png">

2020-03-10 04:29 UTC, melynx requested changes
dynamorio defines X64 for 64bit architectures (both ARM and X86). The #ifdef should be using X64 and you probably only need to #ifdef the buf_store.

Also, merge the X86 support into pypeekaboo and use the arch from metafile to determine how to parse it.

2020-03-10 06:59 UTC, melynx commented
What about the C structs for x86?

2020-03-10 07:03 UTC, jun-zeng commented
It's located in arch folder

2020-03-10 09:20 UTC, melynx requested changes

2020-03-10 09:20 UTC, melynx commented on peekaboo_dr/peekaboo_dr.c
> +	// printf("Peekaboo: Number of SIMD slots: %d\n", MCXT_NUM_SIMD_SLOTS);
Why is this commented. Uncomment this!

2020-03-10 09:26 UTC, mimicji approved these changes
Accept the pull request.
Thanks, Jun!

2020-03-10 09:26 UTC, merged